from django.conf.urls import url
from .views import (
	index,
	dashboard,
	perdas,
	cobertura,
	parto,
	ocorrencia,
	leite,
	venda,
	atividade,
	propriedade,
	coletivo,
	enumerado,

	list_animal_enum,
	list_animal_col,
	list_perdas,
	list_cobertura,
	list_parto,
	list_ocorrencia,
	list_leite,
	list_venda,
	list_atividade,
	list_propriedade,

	edit_animal_enum,
	edit_animal_col,
	edit_perdas,
	edit_cobertura,
	edit_parto,
	edit_ocorrencia,
	edit_leite,
	edit_venda,
	edit_atividade,
	edit_propriedade,
	
	
	)

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^dashboard/$', dashboard, name="dashboard"),
    url(r'^cadastro/enumerado/$', enumerado, name="enumerado"),
    url(r'^cadastro/coletivo/$', coletivo, name="coletivo"),
    url(r'^perdas/$', perdas, name="perdas"),
    url(r'^cobertura/$', cobertura, name="cobertura"),
    url(r'^parto/$', parto, name="parto"),
	url(r'^ocorrencia/$', ocorrencia, name="ocorrencia"),
	url(r'^leite/$', leite, name="leite"),
	url(r'^venda/$', venda, name="venda"),
	url(r'^atividade/$', atividade, name="atividade"),
	url(r'^propriedade/$', propriedade, name="propriedade"),

	url(r'^list/animal-enum/$', list_animal_enum, name="list_animal_enum"),
    url(r'^list/animal-col/$', list_animal_col, name="list_animal_col"),
    url(r'^list/perdas/$', list_perdas, name="list_perdas"),
    url(r'^list/cobertura/$', list_cobertura, name="list_cobertura"),
    url(r'^list/parto/$', list_parto, name="list_parto"),
	url(r'^list/ocorrencia/$', list_ocorrencia, name="list_ocorrencia"),
	url(r'^list/leite/$', list_leite, name="list_leite"),
	url(r'^list/venda/$', list_venda, name="list_venda"),
	url(r'^list/atividade/$', list_atividade, name="list_atividade"),
	url(r'^list/propriedade/$', list_propriedade, name="list_propriedade"),

	url(r'^edit/animal-enum/$', edit_animal_enum, name="edit_animal_enum"),
    url(r'^edit/animal-col/$', edit_animal_col, name="edit_animal_col"),
    url(r'^edit/perdas/$', edit_perdas, name="edit_perdas"),
    url(r'^edit/cobertura/$', edit_cobertura, name="edit_cobertura"),
    url(r'^edit/parto/$', edit_parto, name="edit_parto"),
	url(r'^edit/ocorrencia/$', edit_ocorrencia, name="edit_ocorrencia"),
	url(r'^edit/leite/$', edit_leite, name="edit_leite"),
	url(r'^edit/venda/$', edit_venda, name="edit_venda"),
	url(r'^edit/atividade/$', edit_atividade, name="edit_atividade"),
	url(r'^edit/propriedade/$', edit_propriedade, name="edit_propriedade"),
]
